### ISSUE TITLE
Can't execute binary OSX

### ISSUE THREAD

**Issue by eyrewiut** [PLally/cf_modpack_installer#3]
Hi there, 
I have beee struggling to execute the binary file on osx catalina.. 

I have tried both bash and zsh

The command I am using is: `cf_modpack_installer --modzip "DoIAmCake-3.1.0" --installdir "/Users/eyrewiut/Downloads/DoIAmCake-3.1.0/minecraft"`

The errors I am getting are:
- `zsh: exec format error: cf_modpack_installer`
- `bash: /usr/local/bin/cf_modpack_installer: cannot execute binary file`

Thanks for your help.

**Comment by plally** [comment]
Im sorry I didnt see your issue.
I never uploaded an osx binary to the release. Ill try and get one uploaded tomorrow.

**Comment by plally** [comment]
I added a workflow to compile for darwin, windows and linux
the darwin binary should work for Mac OS X but i have no easy way to test for OS X

**Comment by eyrewiut** [comment]
Thanks for getting back! 
Just tested it and it works perfectly. 😃
